package com.dat.ai_receptionist_web.domain.Training.command;

public enum AttendanceCommandType {
    FACE_CHECK_IN,
    SESSION_ATTENDANCE_BATCH_UPDATE,
    SESSION_ATTENDANCE_STATUS_UPDATE,
    SESSION_ATTENDANCE_EVALUATION_UPDATE,
    SESSION_ATTENDANCE_MANUAL_CREATE,
    SESSION_ATTENDANCE_QUICK_CHECK_IN,
    SESSION_ATTENDANCE_BATCH_INIT,
    SESSION_ATTENDANCE_BULK_DELETE
}
