package com.dat.ai_receptionist_web.enums.Security;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum PermissionDefinition {
    BRANCH_READ("BRANCH_READ", "BRANCH", PermissionAction.READ, "Branch Read"),
    BRANCH_CREATE("BRANCH_CREATE", "BRANCH", PermissionAction.CREATE, "Branch Create"),
    BRANCH_UPDATE("BRANCH_UPDATE", "BRANCH", PermissionAction.UPDATE, "Branch Update"),
    BRANCH_DELETE("BRANCH_DELETE", "BRANCH", PermissionAction.DELETE, "Branch Delete"),
    PERSON_READ("PERSON_READ", "PERSON", PermissionAction.READ, "Person Read"),
    PERSON_CREATE("PERSON_CREATE", "PERSON", PermissionAction.CREATE, "Person Create"),
    PERSON_UPDATE("PERSON_UPDATE", "PERSON", PermissionAction.UPDATE, "Person Update"),
    PERSON_DELETE("PERSON_DELETE", "PERSON", PermissionAction.DELETE, "Person Delete"),
    POSITION_READ("POSITION_READ", "POSITION", PermissionAction.READ, "Position Read"),
    POSITION_CREATE("POSITION_CREATE", "POSITION", PermissionAction.CREATE, "Position Create"),
    POSITION_UPDATE("POSITION_UPDATE", "POSITION", PermissionAction.UPDATE, "Position Update"),
    POSITION_DELETE("POSITION_DELETE", "POSITION", PermissionAction.DELETE, "Position Delete"),
    USER_PERSON_READ("USER_PERSON_READ", "USER_PERSON", PermissionAction.READ, "User Person Read"),
    USER_PERSON_CREATE("USER_PERSON_CREATE", "USER_PERSON", PermissionAction.CREATE, "User Person Create"),
    USER_PERSON_UPDATE("USER_PERSON_UPDATE", "USER_PERSON", PermissionAction.UPDATE, "User Person Update"),
    USER_PERSON_DELETE("USER_PERSON_DELETE", "USER_PERSON", PermissionAction.DELETE, "User Person Delete"),
    CLASS_SCHEDULE_READ("CLASS_SCHEDULE_READ", "CLASS_SCHEDULE", PermissionAction.READ, "Class Schedule Read"),
    CLASS_SCHEDULE_CREATE("CLASS_SCHEDULE_CREATE", "CLASS_SCHEDULE", PermissionAction.CREATE, "Class Schedule Create"),
    CLASS_SCHEDULE_UPDATE("CLASS_SCHEDULE_UPDATE", "CLASS_SCHEDULE", PermissionAction.UPDATE, "Class Schedule Update"),
    CLASS_SCHEDULE_DELETE("CLASS_SCHEDULE_DELETE", "CLASS_SCHEDULE", PermissionAction.DELETE, "Class Schedule Delete"),
    COURSE_READ("COURSE_READ", "COURSE", PermissionAction.READ, "Course Read"),
    COURSE_CREATE("COURSE_CREATE", "COURSE", PermissionAction.CREATE, "Course Create"),
    COURSE_UPDATE("COURSE_UPDATE", "COURSE", PermissionAction.UPDATE, "Course Update"),
    COURSE_DELETE("COURSE_DELETE", "COURSE", PermissionAction.DELETE, "Course Delete"),
    COURSE_PRICE_READ("COURSE_PRICE_READ", "COURSE_PRICE", PermissionAction.READ, "Course Price Read"),
    COURSE_PRICE_CREATE("COURSE_PRICE_CREATE", "COURSE_PRICE", PermissionAction.CREATE, "Course Price Create"),
    COURSE_PRICE_UPDATE("COURSE_PRICE_UPDATE", "COURSE_PRICE", PermissionAction.UPDATE, "Course Price Update"),
    COURSE_PRICE_DELETE("COURSE_PRICE_DELETE", "COURSE_PRICE", PermissionAction.DELETE, "Course Price Delete"),
    WALLET_READ("WALLET_READ", "WALLET", PermissionAction.READ, "Wallet Read"),
    WALLET_CREATE("WALLET_CREATE", "WALLET", PermissionAction.CREATE, "Wallet Create"),
    WALLET_UPDATE("WALLET_UPDATE", "WALLET", PermissionAction.UPDATE, "Wallet Update"),
    WALLET_DELETE("WALLET_DELETE", "WALLET", PermissionAction.DELETE, "Wallet Delete"),
    WALLET_TRANSACTION_READ("WALLET_TRANSACTION_READ", "WALLET_TRANSACTION", PermissionAction.READ, "Wallet Transaction Read"),
    WALLET_TRANSACTION_CREATE("WALLET_TRANSACTION_CREATE", "WALLET_TRANSACTION", PermissionAction.CREATE, "Wallet Transaction Create"),
    WALLET_TRANSACTION_UPDATE("WALLET_TRANSACTION_UPDATE", "WALLET_TRANSACTION", PermissionAction.UPDATE, "Wallet Transaction Update"),
    WALLET_TRANSACTION_DELETE("WALLET_TRANSACTION_DELETE", "WALLET_TRANSACTION", PermissionAction.DELETE, "Wallet Transaction Delete"),
    COURSE_PURCHASE_READ("COURSE_PURCHASE_READ", "COURSE_PURCHASE", PermissionAction.READ, "Course Purchase Read"),
    COURSE_PURCHASE_CREATE("COURSE_PURCHASE_CREATE", "COURSE_PURCHASE", PermissionAction.CREATE, "Course Purchase Create"),
    COURSE_PURCHASE_UPDATE("COURSE_PURCHASE_UPDATE", "COURSE_PURCHASE", PermissionAction.UPDATE, "Course Purchase Update"),
    COURSE_PURCHASE_DELETE("COURSE_PURCHASE_DELETE", "COURSE_PURCHASE", PermissionAction.DELETE, "Course Purchase Delete"),
    FITNESS_READ("FITNESS_READ", "FITNESS", PermissionAction.READ, "Fitness Read"),
    FITNESS_CREATE("FITNESS_CREATE", "FITNESS", PermissionAction.CREATE, "Fitness Create"),
    FITNESS_UPDATE("FITNESS_UPDATE", "FITNESS", PermissionAction.UPDATE, "Fitness Update"),
    FITNESS_DELETE("FITNESS_DELETE", "FITNESS", PermissionAction.DELETE, "Fitness Delete"),
    FITNESS_RECORD_READ("FITNESS_RECORD_READ", "FITNESS_RECORD", PermissionAction.READ, "Fitness Record Read"),
    FITNESS_RECORD_CREATE("FITNESS_RECORD_CREATE", "FITNESS_RECORD", PermissionAction.CREATE, "Fitness Record Create"),
    FITNESS_RECORD_UPDATE("FITNESS_RECORD_UPDATE", "FITNESS_RECORD", PermissionAction.UPDATE, "Fitness Record Update"),
    FITNESS_RECORD_DELETE("FITNESS_RECORD_DELETE", "FITNESS_RECORD", PermissionAction.DELETE, "Fitness Record Delete"),
    NOTIFICATION_READ("NOTIFICATION_READ", "NOTIFICATION", PermissionAction.READ, "Notification Read"),
    NOTIFICATION_CREATE("NOTIFICATION_CREATE", "NOTIFICATION", PermissionAction.CREATE, "Notification Create"),
    NOTIFICATION_UPDATE("NOTIFICATION_UPDATE", "NOTIFICATION", PermissionAction.UPDATE, "Notification Update"),
    NOTIFICATION_DELETE("NOTIFICATION_DELETE", "NOTIFICATION", PermissionAction.DELETE, "Notification Delete"),
    NOTIFICATION_RECIPIENT_READ("NOTIFICATION_RECIPIENT_READ", "NOTIFICATION_RECIPIENT", PermissionAction.READ, "Notification Recipient Read"),
    NOTIFICATION_RECIPIENT_CREATE("NOTIFICATION_RECIPIENT_CREATE", "NOTIFICATION_RECIPIENT", PermissionAction.CREATE, "Notification Recipient Create"),
    NOTIFICATION_RECIPIENT_UPDATE("NOTIFICATION_RECIPIENT_UPDATE", "NOTIFICATION_RECIPIENT", PermissionAction.UPDATE, "Notification Recipient Update"),
    NOTIFICATION_RECIPIENT_DELETE("NOTIFICATION_RECIPIENT_DELETE", "NOTIFICATION_RECIPIENT", PermissionAction.DELETE, "Notification Recipient Delete"),
    AUTH_SESSION_READ("AUTH_SESSION_READ", "AUTH_SESSION", PermissionAction.READ, "Auth Session Read"),
    AUTH_SESSION_CREATE("AUTH_SESSION_CREATE", "AUTH_SESSION", PermissionAction.CREATE, "Auth Session Create"),
    AUTH_SESSION_UPDATE("AUTH_SESSION_UPDATE", "AUTH_SESSION", PermissionAction.UPDATE, "Auth Session Update"),
    AUTH_SESSION_DELETE("AUTH_SESSION_DELETE", "AUTH_SESSION", PermissionAction.DELETE, "Auth Session Delete"),
    PERMISSION_READ("PERMISSION_READ", "PERMISSION", PermissionAction.READ, "Permission Read"),
    PERMISSION_CREATE("PERMISSION_CREATE", "PERMISSION", PermissionAction.CREATE, "Permission Create"),
    PERMISSION_UPDATE("PERMISSION_UPDATE", "PERMISSION", PermissionAction.UPDATE, "Permission Update"),
    PERMISSION_DELETE("PERMISSION_DELETE", "PERMISSION", PermissionAction.DELETE, "Permission Delete"),
    ROLE_READ("ROLE_READ", "ROLE", PermissionAction.READ, "Role Read"),
    ROLE_CREATE("ROLE_CREATE", "ROLE", PermissionAction.CREATE, "Role Create"),
    ROLE_UPDATE("ROLE_UPDATE", "ROLE", PermissionAction.UPDATE, "Role Update"),
    ROLE_DELETE("ROLE_DELETE", "ROLE", PermissionAction.DELETE, "Role Delete"),
    USER_ROLE_READ("USER_ROLE_READ", "USER_ROLE", PermissionAction.READ, "User Role Read"),
    USER_ROLE_CREATE("USER_ROLE_CREATE", "USER_ROLE", PermissionAction.CREATE, "User Role Create"),
    USER_ROLE_UPDATE("USER_ROLE_UPDATE", "USER_ROLE", PermissionAction.UPDATE, "User Role Update"),
    USER_ROLE_DELETE("USER_ROLE_DELETE", "USER_ROLE", PermissionAction.DELETE, "User Role Delete"),
    USER_READ("USER_READ", "USER", PermissionAction.READ, "User Read"),
    USER_CREATE("USER_CREATE", "USER", PermissionAction.CREATE, "User Create"),
    USER_UPDATE("USER_UPDATE", "USER", PermissionAction.UPDATE, "User Update"),
    USER_DELETE("USER_DELETE", "USER", PermissionAction.DELETE, "User Delete"),
    CLASS_SESSION_READ("CLASS_SESSION_READ", "CLASS_SESSION", PermissionAction.READ, "Class Session Read"),
    CLASS_SESSION_CREATE("CLASS_SESSION_CREATE", "CLASS_SESSION", PermissionAction.CREATE, "Class Session Create"),
    CLASS_SESSION_UPDATE("CLASS_SESSION_UPDATE", "CLASS_SESSION", PermissionAction.UPDATE, "Class Session Update"),
    CLASS_SESSION_DELETE("CLASS_SESSION_DELETE", "CLASS_SESSION", PermissionAction.DELETE, "Class Session Delete"),
    COURSE_STAFF_ASSIGNMENT_READ("COURSE_STAFF_ASSIGNMENT_READ", "COURSE_STAFF_ASSIGNMENT", PermissionAction.READ, "Course Staff Assignment Read"),
    COURSE_STAFF_ASSIGNMENT_CREATE("COURSE_STAFF_ASSIGNMENT_CREATE", "COURSE_STAFF_ASSIGNMENT", PermissionAction.CREATE, "Course Staff Assignment Create"),
    COURSE_STAFF_ASSIGNMENT_UPDATE("COURSE_STAFF_ASSIGNMENT_UPDATE", "COURSE_STAFF_ASSIGNMENT", PermissionAction.UPDATE, "Course Staff Assignment Update"),
    COURSE_STAFF_ASSIGNMENT_DELETE("COURSE_STAFF_ASSIGNMENT_DELETE", "COURSE_STAFF_ASSIGNMENT", PermissionAction.DELETE, "Course Staff Assignment Delete"),
    COACH_TIMESHEET_READ("COACH_TIMESHEET_READ", "COACH_TIMESHEET", PermissionAction.READ, "Coach Timesheet Read"),
    COACH_TIMESHEET_CREATE("COACH_TIMESHEET_CREATE", "COACH_TIMESHEET", PermissionAction.CREATE, "Coach Timesheet Create"),
    COACH_TIMESHEET_UPDATE("COACH_TIMESHEET_UPDATE", "COACH_TIMESHEET", PermissionAction.UPDATE, "Coach Timesheet Update"),
    COACH_TIMESHEET_DELETE("COACH_TIMESHEET_DELETE", "COACH_TIMESHEET", PermissionAction.DELETE, "Coach Timesheet Delete"),
    BELT_EXAM_READ("BELT_EXAM_READ", "BELT_EXAM", PermissionAction.READ, "Belt Exam Read"),
    BELT_EXAM_CREATE("BELT_EXAM_CREATE", "BELT_EXAM", PermissionAction.CREATE, "Belt Exam Create"),
    BELT_EXAM_UPDATE("BELT_EXAM_UPDATE", "BELT_EXAM", PermissionAction.UPDATE, "Belt Exam Update"),
    BELT_EXAM_DELETE("BELT_EXAM_DELETE", "BELT_EXAM", PermissionAction.DELETE, "Belt Exam Delete"),
    LEAVE_REQUEST_READ("LEAVE_REQUEST_READ", "LEAVE_REQUEST", PermissionAction.READ, "Leave Request Read"),
    LEAVE_REQUEST_CREATE("LEAVE_REQUEST_CREATE", "LEAVE_REQUEST", PermissionAction.CREATE, "Leave Request Create"),
    LEAVE_REQUEST_UPDATE("LEAVE_REQUEST_UPDATE", "LEAVE_REQUEST", PermissionAction.UPDATE, "Leave Request Update"),
    LEAVE_REQUEST_DELETE("LEAVE_REQUEST_DELETE", "LEAVE_REQUEST", PermissionAction.DELETE, "Leave Request Delete"),
    SESSION_ATTENDANCE_READ("SESSION_ATTENDANCE_READ", "SESSION_ATTENDANCE", PermissionAction.READ, "Session Attendance Read"),
    SESSION_ATTENDANCE_CREATE("SESSION_ATTENDANCE_CREATE", "SESSION_ATTENDANCE", PermissionAction.CREATE, "Session Attendance Create"),
    SESSION_ATTENDANCE_UPDATE("SESSION_ATTENDANCE_UPDATE", "SESSION_ATTENDANCE", PermissionAction.UPDATE, "Session Attendance Update"),
    SESSION_ATTENDANCE_DELETE("SESSION_ATTENDANCE_DELETE", "SESSION_ATTENDANCE", PermissionAction.DELETE, "Session Attendance Delete"),
    STUDENT_ENROLLMENT_READ("STUDENT_ENROLLMENT_READ", "STUDENT_ENROLLMENT", PermissionAction.READ, "Student Enrollment Read"),
    STUDENT_ENROLLMENT_CREATE("STUDENT_ENROLLMENT_CREATE", "STUDENT_ENROLLMENT", PermissionAction.CREATE, "Student Enrollment Create"),
    STUDENT_ENROLLMENT_UPDATE("STUDENT_ENROLLMENT_UPDATE", "STUDENT_ENROLLMENT", PermissionAction.UPDATE, "Student Enrollment Update"),
    STUDENT_ENROLLMENT_DELETE("STUDENT_ENROLLMENT_DELETE", "STUDENT_ENROLLMENT", PermissionAction.DELETE, "Student Enrollment Delete"),
    WALLET_TOP_UP_CREATE("WALLET_TOP_UP_CREATE", "WALLET", PermissionAction.CREATE, "Wallet Top Up Create"),
    WALLET_REFUND_CREATE("WALLET_REFUND_CREATE", "WALLET", PermissionAction.CREATE, "Wallet Refund Create");

    private final String code;
    private final String model;
    private final PermissionAction action;
    private final String description;
}
